apiVersion: apps/v1
kind: Deployment
metadata:
  name: eda-deployment
  labels:
    app: eda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eda
  template:
    metadata:
      labels:
        app: eda
    spec:
      containers:
      - name: eda
        image: quay.io/dcurran/eda-kafka-test:latest
        env:
        - name: RULEBOOK
          value: "kafka-example/rulebook-kafka.yml"
        - name: KAFKA_HOST
          value: "eda-test-kafka-bootstrap.eda-test.svc.cluster.local"
        - name: KAFKA_PORT
          value: "9092"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: eda-webhook
spec:
  selector:
    app: eda
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
